<file> ::= <lines>

<lines> ::= <line> | <line> <lines>
<line> ::= <blankline> | <commentline> | <propertyline>

<blankline> ::= "\n"
<propertyline> ::= <key> "=" <values>
<key> ::= <keysegment> | <keysegment> "." <key>
<keysegment> ::= <identifier> | <number>
<identifier> ::= <letter> | <idchar> <identifier>
<idchar> ::= <letter> | <digit> | "_"
<number> ::= <digit> | <digit> <number>
<values> ::= <value> | <value> "," <values>
<value> ::= <valuechar> | <valuechar> <value>
<valuechar> ::= <letter> | <digit> | " " | "_" | "-" | "." | "/"

<commentline> ::= "#" <commenttext> | "#"
<commenttext> ::= <char> | <char> <commenttext>
<char> ::= <letter> | <digit> | " " | "_" | "-" | "." | "," | "!" | "?" | ":" | ";" | "'"  | "/" | "(" | ")" | "[" | "]" | "{" | "}" | "<" | ">" | "|" | "`" | "~" | "@" | "#" | "$" | "%" | "^" | "&" | "*" | "+" | "="

<letter> ::= "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" | "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"

<digit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"